**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [2]:
import numpy as np

### `Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [ ]:
a = np.nan * np.empty(10) # anything operated with nan will result in nan
# a = np.nan * np.ones(10) # this line will give the same results
a[4] = 1
a

array([nan, nan, nan, nan,  1., nan, nan, nan, nan, nan])

In [ ]:
a = np.zeros(4, int)
np.concatenate([a, np.ones(1), np.zeros(5)])

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [45]:
a = np.zeros(10)
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

### `Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [79]:
a, b = map(int, input("Enter two numbers seperated by a space.").split(sep=" "))
# a, b = int(a), int(b)
arr = np.random.randint(1, 50, a * b).reshape(a, b)
print(f"{arr} \n Avg: {arr.sum()/(a*b)}")  # could've used arr.mean(), but the former is used for understanding
# print(arr.mean())

[[38 14 36]
 [40 15 16]
 [38 37 28]
 [45 37 28]] 
 Avg: 31.0


### `Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [9]:
def hollowArray(a, b):
        # initiating array of a*b with zeroes
        arr = np.zeros((a, b))
        
        # setting the first and last column to 1
        arr[0, :] = 1
        arr[-1, :] = 1

        # setting the remaining col's first and last element as 1
        arr[:, 0] = 1
        arr[:, -1] = 1

        return arr

hollowArray(10, 8)

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

### `Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [89]:
arr = np.linspace(0, 1, 12)[1:-1]; print(arr)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


### `Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [23]:
# no

### `Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [97]:
arr = np.zeros((5, 5), dtype=int)
arr += np.arange(5)
arr

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

### `Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [105]:
a = np.random.randint(1, 100, (10, 2))
p = np.array([2, 3])
print(a)
# sqrt((2-18) ** 2 + (3-59) ** 2)
np.sqrt(np.sum((a - p) ** 2, axis=1)).astype(int)

[[40 29]
 [ 4 75]
 [42 28]
 [23 93]
 [38 54]
 [60 21]
 [ 3 19]
 [62 25]
 [13 17]
 [48 85]]


array([46, 72, 47, 92, 62, 60, 16, 63, 17, 94])

### `Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [2]:
arr = np.arange(6*7*8).reshape(6, 7, 8)
print(arr)
print(f"\nIndex of 100th element is: {np.where(arr == 100)}")

[[[  0   1   2   3   4   5   6   7]
  [  8   9  10  11  12  13  14  15]
  [ 16  17  18  19  20  21  22  23]
  [ 24  25  26  27  28  29  30  31]
  [ 32  33  34  35  36  37  38  39]
  [ 40  41  42  43  44  45  46  47]
  [ 48  49  50  51  52  53  54  55]]

 [[ 56  57  58  59  60  61  62  63]
  [ 64  65  66  67  68  69  70  71]
  [ 72  73  74  75  76  77  78  79]
  [ 80  81  82  83  84  85  86  87]
  [ 88  89  90  91  92  93  94  95]
  [ 96  97  98  99 100 101 102 103]
  [104 105 106 107 108 109 110 111]]

 [[112 113 114 115 116 117 118 119]
  [120 121 122 123 124 125 126 127]
  [128 129 130 131 132 133 134 135]
  [136 137 138 139 140 141 142 143]
  [144 145 146 147 148 149 150 151]
  [152 153 154 155 156 157 158 159]
  [160 161 162 163 164 165 166 167]]

 [[168 169 170 171 172 173 174 175]
  [176 177 178 179 180 181 182 183]
  [184 185 186 187 188 189 190 191]
  [192 193 194 195 196 197 198 199]
  [200 201 202 203 204 205 206 207]
  [208 209 210 211 212 213 214 215]
  [216 217 218 219 220

### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [ ]:
input_string = "1 2 3 4 -8 -10"
inp_list = input_string.split(sep=' ')
print(inp_list)
arr = np.asarray(inp_list)
print(np.flip(arr)) # or use the below code
# arr = arr[::-1]
# print('reversed: ', arr)

['1', '2', '3', '4', '-8', '-10']
['-10' '-8' '4' '3' '2' '1']


### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [8]:
arr = np.arange(10)
print(f"{arr} \nElements Count: {np.size(arr)}")

[0 1 2 3 4 5 6 7 8 9] 
Elements Count: 10


### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [60]:
def softmax(arr):
    try:
        if np.ndim(arr) != 1:
            raise ValueError('multidim array caught')

        # implementing the formula
        exponents = np.e ** arr
        sumexp = sum(exponents)
        result = exponents/sumexp
        return result        

    except ValueError:
        print(f"array \n{arr} has multiple dim; multidim array not allowed")

softmax(np.array([86.03331084, 37.7285648,  48.64908087, 87.16563062, 38.40852563, 37.20006318]))
# softmax(np.array([-2, 1, 0]))

array([2.43733248e-01, 2.56112114e-22, 1.41628283e-17, 7.56266752e-01,
       5.05514197e-22, 1.50974911e-22])

### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [35]:
def verticalStacker(*arrays):
    print(arrays)
    try:
        if not all(isinstance(arr, np.ndarray) for arr in arrays):
            raise TypeError
        stacked_array = np.vstack(arrays)
        return stacked_array
    except TypeError:
        print('one or more arguements are not of type numpy.ndarray')

a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
c = np.array(['a', 'b', 'c', 'd'])
verticalStacker(a, a, b, c) 

(array([1, 2, 3, 4]), array([1, 2, 3, 4]), array([5, 6, 7, 8]), array(['a', 'b', 'c', 'd'], dtype='<U1'))


array([['1', '2', '3', '4'],
       ['1', '2', '3', '4'],
       ['5', '6', '7', '8'],
       ['a', 'b', 'c', 'd']], dtype='<U21')

### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [ ]:
def date_array(**dates):
    try:
        if len(dates) != 2:
            raise ValueError
        
    except ValueError:
        return f"Only and exactly 2 dates can be sent as seperate strings."

### `Q-14:` Subtract the mean of each row from a matrix.

In [108]:
mat = np.random.randint(1, 100, (5, 5))
print(mat)
print(mat - mat.mean(axis=1, keepdims=True))

[[44 61 61 83 27]
 [78 67 68 44 70]
 [73 96 14 76 90]
 [38 47 76 20 68]
 [84  8  7 28 11]]
[[-11.2   5.8   5.8  27.8 -28.2]
 [ 12.6   1.6   2.6 -21.4   4.6]
 [  3.2  26.2 -55.8   6.2  20.2]
 [-11.8  -2.8  26.2 -29.8  18.2]
 [ 56.4 -19.6 -20.6   0.4 -16.6]]


### `Q-15:` Swap column-1 of array with column-2 in the array.

In [113]:
a = np.arange(9).reshape(3, 3)
a[:, [0, 2, 1]]

array([[0, 2, 1],
       [3, 5, 4],
       [6, 8, 7]])

### `Q-16:` Replace odd elements in arrays with -1.

In [125]:
arr = np.arange(10)
print(f"{arr} \n{arr % 2 == 0}")
arr[arr % 2 == 0] = -1
print(arr)

[0 1 2 3 4 5 6 7 8 9] 
[ True False  True False  True False  True False  True False]
[-1  1 -1  3 -1  5 -1  7 -1  9]


### `Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [129]:
arr1 = np.array([6, 3, 1, 5, 8])
arr2 = np.array([3, 2, 1, 7, 2])
arr1[arr2 > arr1] = arr2[arr1 < arr2]
arr1

array([6, 3, 1, 7, 8])

### `Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [130]:
# Given
arr1 = np.random.randint(low=1, high=10000, size=40).reshape(8, 5)
arr1

array([[4488, 8356, 1220, 7167, 4034],
       [2055, 6145, 2920, 8357, 6250],
       [7249, 3429, 9884, 4666, 9873],
       [5553, 6465, 9380, 2214,  317],
       [9669, 9893, 6385, 9619, 2555],
       [ 352, 8958, 2712, 8766, 7053],
       [7466, 6010,  649, 5565, 9561],
       [8414, 2386, 1395, 2188, 9024]])

In [131]:
arr1[:, ::2]

array([[4488, 1220, 4034],
       [2055, 2920, 6250],
       [7249, 9884, 9873],
       [5553, 9380,  317],
       [9669, 6385, 2555],
       [ 352, 2712, 7053],
       [7466,  649, 9561],
       [8414, 1395, 9024]])

In [133]:
(arr1 - arr1.min())/(arr1.max() - arr1.min())

array([[0.43556809, 0.83949457, 0.09429825, 0.71532999, 0.38815789],
       [0.18149541, 0.60860485, 0.2718254 , 0.839599  , 0.61956976],
       [0.72389307, 0.32497911, 0.99906015, 0.45415622, 0.99791145],
       [0.54678363, 0.64202172, 0.94642857, 0.19809942, 0.        ],
       [0.97660819, 1.        , 0.6336675 , 0.9713868 , 0.23370927],
       [0.00365497, 0.90236007, 0.25010443, 0.88230994, 0.70342523],
       [0.74655388, 0.5945071 , 0.03467001, 0.54803676, 0.96532999],
       [0.84555138, 0.21606099, 0.1125731 , 0.19538429, 0.9092523 ]])

### `Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [140]:
arr = np.array([12, 34, 40, 7, 1, 0]); n = 3
arr_sorted = np.sort(arr)
print(arr_sorted[n])

12


### `Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [3]:
a = np.array([1, 2, 3])
# arr = np.arange(a.any(a), 9, 1, dtype=int)
# arr
np.hstack([np.repeat(a, 3), np.tile(a, 3)])

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])