# Session 15 Numpy Tricks

## 📘 **1. `np.sort()`**
**Purpose**: Returns a **sorted copy** of an array.

### 📌 Syntax:
```python
np.sort(array, axis=-1, kind='quicksort')
```

### ✅ Parameters:
- `array`: Input array to be sorted.
- `axis`: Axis along which to sort. Default is `-1` (last axis).
- `kind`: Sorting algorithm. Options: `'quicksort'`, `'mergesort'`, `'heapsort'`, `'stable'`.

### 🧠 Notes:
- Does **not** modify the original array.
- Can sort both 1D and 2D arrays.
- Reversing the result using slicing (`[::-1]`) gives descending order.

### 🧪 Example:

```python
a = np.random.randint(1, 100, 15)
print(np.sort(a))           # ascending
print(np.sort(a)[::-1])     # descending

b = np.random.randint(1, 100, 24).reshape(6, 4)
print(np.sort(b, axis=0))   # column-wise sort
print(np.sort(b, axis=1))   # row-wise sort
```

---

## 📘 **2. `np.append()`**
**Purpose**: Appends values to the end of an array.

### 📌 Syntax:
```python
np.append(arr, values, axis=None)
```

### ✅ Parameters:
- `arr`: Array to append values to.
- `values`: Values to append.
- `axis`: Axis along which values are appended. If `None`, array is flattened first.

### 🧠 Notes:
- Returns a **new array**, original is unchanged.
- Useful for simple append operations; for complex joins, use `concatenate`.

### 🧪 Example:
```python
np.append(a, 200)

# Appending a column to a 2D array
new_col = np.random.randint(1, 100, (b.shape[0], 1))
np.append(b, new_col, axis=1)
```

---

## 📘 **3. `np.concatenate()`**
**Purpose**: Joins a sequence of arrays along an existing axis.

### 📌 Syntax:
```python
np.concatenate((array1, array2), axis=0)
```

### ✅ Parameters:
- Arrays must have the same shape except in the concatenation axis.

### 🧠 Notes:
- Can be used as a substitute for `vstack()` and `hstack()`.
- Unlike `append`, `concatenate` requires shape consistency along non-concatenation axes.

### 🧪 Example:
```python
c = np.arange(6).reshape(2, 3)
d = np.arange(6, 12).reshape(2, 3)

np.concatenate((c, d), axis=0)  # vertical stack
np.concatenate((c, d), axis=1)  # horizontal stack
```

---

## 📘 **4. `np.unique()`**
**Purpose**: Finds unique elements of an array.

### 📌 Syntax:
```python
np.unique(array, return_index=False, return_counts=False)
```

### ✅ Parameters:
- `return_index`: If `True`, also return indices of the input array.
- `return_counts`: If `True`, also return counts of unique values.

### 🧠 Use Cases:
- Removing duplicates.
- Frequency analysis.

### 🧪 Example:
```python
e = np.array([1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6])
np.unique(e)
```

---

## 📘 **5. `np.expand_dims()`**
**Purpose**: Expands the shape of an array.

### 📌 Syntax:
```python
np.expand_dims(array, axis)
```

### ✅ Parameters:
- `axis`: Position where new axis is inserted.

### 🧠 Use Cases:
- Preparing data for models (e.g., converting shape `(N,)` to `(N, 1)`).
- Required for broadcasting and tensor operations.

### 🧪 Example:
```python
print(a.shape)                     # (15,)
np.expand_dims(a, axis=1).shape    # (15, 1)
```

---

## 📘 **6. `np.where()`**
**Purpose**: Conditional filtering or selection.

### 📌 Syntax:
```python
np.where(condition, [x, y])
```

### ✅ Parameters:
- `condition`: Boolean expression.
- `x`, `y`: Optional. Elements from `x` are selected where condition is True, and from `y` otherwise.

### 🧠 Use Cases:
- Extracting indices.
- Replacing values conditionally (vectorized operations).

### 🧪 Examples:
```python
np.where(a > 50)              # Indices where a > 50
np.where(a > 50, 0, a)        # Replace all > 50 with 0
np.where(a % 2 == 0, 0, a)    # Replace even values with 0
```

---

In [9]:
import numpy as np

e = np.array([1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6])
print(np.unique(e))
np.cumsum(np.unique(e))

[1 2 3 4 5 6]


array([ 1,  3,  6, 10, 15, 21])

In [ ]:
np.expand_dims(e, -1)

array([[1],
       [1],
       [2],
       [2],
       [3],
       [3],
       [4],
       [4],
       [5],
       [5],
       [6],
       [6]])

## 📊 **`np.argmax()`**
**Purpose:** Returns the index of the **maximum value** in an array.

### 📌 Syntax:
```python
np.argmax(a, axis=None)
```

### 📎 Parameters:
- `a`: input array.
- `axis`: optional. By default, flattens the array. If specified, returns indices along that axis.

### 🧠 Use Case:
Helpful in classification problems where you want to find the class with the maximum probability (like in softmax output).

### ✅ Example:

```python
a = np.array([10, 20, 5, 40])
np.argmax(a)  # Output: 3 (index of 40)
```

**With 2D matrix:**
```python
b = np.random.randint(1, 100, 24).reshape(6, 4)
np.argmax(b, axis=0)  # Max indices column-wise
np.argmax(b, axis=1)  # Max indices row-wise
```

---

## 🔽 **`np.argmin()`**
Same as `argmax`, but returns the **index of the minimum value**.

---

## ➕ **`np.cumsum()`**
**Purpose:** Computes the **cumulative sum** of elements.

### 📌 Syntax:
```python
np.cumsum(a, axis=None)
```

### 🧠 Use Case:
- In statistics for calculating cumulative distributions.
- In finance for running totals of revenue, expenditure, etc.

### ✅ Example:
```python
a = np.array([1, 2, 3])
np.cumsum(a)  # Output: [1, 3, 6]
```

---

## ✖️ **`np.cumprod()`**
**Purpose:** Computes the **cumulative product** of elements.

### ✅ Example:
```python
a = np.array([1, 2, 3])
np.cumprod(a)  # Output: [1, 2, 6]
```

---

## 📈 **`np.percentile()`**
**Purpose:** Computes the nth **percentile** of data.

### 📌 Syntax:
```python
np.percentile(a, q)
```

### 📎 Parameters:
- `a`: input array.
- `q`: percentile value between 0 and 100.

### 🧠 What is Percentile?
It indicates the value **below which a given percentage** of observations fall.

### 📊 Use Case:
Used in outlier detection, descriptive statistics, and normalization.

### ✅ Example:
```python
a = np.array([1, 2, 3, 4, 5])
np.percentile(a, 50)  # Output: 3 (median)
```

### 🧮 Percentile Formula:
If `n` is total number of observations and `P` is the percentile rank:

```
Percentile = (P / 100) * n-th value in sorted data
```

---

## 📊 **`np.histogram()`**
**Purpose:** Computes histogram of a dataset. Helps visualize frequency distribution.

### 📌 Syntax:
```python
np.histogram(a, bins)
```

### 📎 Parameters:
- `a`: input array.
- `bins`: sequence defining bin edges.

### ✅ Example:
```python
a = np.random.randint(0, 100, 15)
hist, bin_edges = np.histogram(a, bins=[0,10,20,30,40,50,60,70,80,90,100])
print(hist)
print(bin_edges)
```

### 🧠 Output Explanation:
- `hist`: frequency count in each bin.
- `bin_edges`: boundary values of each bin.
This is useful in **data preprocessing and visualization**.

---

## 🔗 **`np.corrcoef()`**
**Purpose:** Returns the **Pearson correlation coefficient matrix**.

### 📌 Syntax:
```python
np.corrcoef(x, y)
```

### 🧠 What is Correlation?
A measure of linear relationship between two datasets:
- `+1`: strong positive correlation
- `0`: no correlation
- `-1`: strong negative correlation

### ✅ Example:
```python
salary = np.array([20000, 40000, 25000, 35000, 60000])
experience = np.array([1, 3, 2, 4, 2])

np.corrcoef(salary, experience)
```

### 📎 Output:
A 2x2 matrix:
- `corrcoef[0, 1]` or `corrcoef[1, 0]` gives the **correlation coefficient** between salary and experience.

---

Perfect! You've included a rich set of NumPy functions that are super useful in data science. Here's the continuation with explanations, syntax, parameters, use cases, and relevant examples for each function:

---

### ✅ `np.isin()`
**Purpose:** Checks whether each element of one array is present in another array.

**Syntax:**
```python
np.isin(element, test_elements)
```

**Parameters:**
- `element`: array-like — Input array.
- `test_elements`: array-like — Values to test against.
- Returns: Boolean array of the same shape as `element`.

**Use Cases in Data Science:**
- Filtering specific values (e.g., valid categories, outliers, missing value placeholders).

**Example:**
```python
a = np.array([10, 25, 30, 45, 50])
items = [10, 20, 30, 40, 50]
print(np.isin(a, items))  # [ True False  True False  True ]
print(a[np.isin(a, items)])  # [10 30 50]
```

---

### 🔁 `np.flip()`
**Purpose:** Reverses the order of elements in an array along a specified axis.

**Syntax:**
```python
np.flip(m, axis=None)
```

**Parameters:**
- `m`: array-like — Input array.
- `axis`: int, optional — Axis to flip. Default is `None`, which reverses all axes.

**Use Cases:**
- Time series reversal.
- Image processing (mirror flipping).
- Data augmentation in machine learning.

**Example:**
```python
a = np.array([1, 2, 3])
np.flip(a)  # [3 2 1]

b = np.array([[1, 2], [3, 4]])
np.flip(b, axis=0)  # Flips rows
np.flip(b, axis=1)  # Flips columns
```

---

### 📝 `np.put()`
**Purpose:** Replaces specific elements in a flattened array with new values.

**Syntax:**
```python
np.put(arr, indices, values)
```

**Parameters:**
- `arr`: ndarray — Array to modify (modifies in-place).
- `indices`: array-like — Indices where to place `values`.
- `values`: array-like — Values to insert.

**Important:** Works on the flattened version of `arr`.

**Example:**
```python
a = np.array([1, 2, 3, 4])
np.put(a, [0, 2], [100, 300])
print(a)  # [100, 2, 300, 4]
```

---

### 🗑️ `np.delete()`
**Purpose:** Returns a new array with specified elements deleted along an axis.

**Syntax:**
```python
np.delete(arr, obj, axis=None)
```

**Parameters:**
- `arr`: array-like — Input array.
- `obj`: int or array of ints — Indices to delete.
- `axis`: int, optional — Axis along which to delete.

**Note:** It does not change the original array.

**Example:**
```python
a = np.array([10, 20, 30, 40, 50])
print(np.delete(a, [1, 3]))  # [10 30 50]
```

---

## 🧮 Set Operations in NumPy

| Function           | Description |
|--------------------|-------------|
| `np.union1d()`     | Union of two arrays. |
| `np.intersect1d()` | Intersection of two arrays. |
| `np.setdiff1d()`   | Elements in one array but not the other. |
| `np.setxor1d()`    | Elements in either array, but not both. |
| `np.in1d()`        | Check whether elements of one array are in another (returns boolean array). |

**Example:**
```python
m = np.array([1, 2, 3, 4, 5])
n = np.array([3, 4, 5, 6, 7])

np.union1d(m, n)       # [1 2 3 4 5 6 7]
np.intersect1d(m, n)   # [3 4 5]
np.setdiff1d(n, m)     # [6 7]
np.setxor1d(m, n)      # [1 2 6 7]
m[np.in1d(m, [1])]     # [1]
```

**Use Cases:**
- Set-based filtering
- Feature comparison
- Removing duplicates or finding unique overlaps

---

### 📉 `np.clip()`
**Purpose:** Limits values in an array within a defined range.

**Syntax:**
```python
np.clip(arr, a_min, a_max)
```

**Parameters:**
- `arr`: array-like — Input array.
- `a_min`: scalar — Minimum allowed value.
- `a_max`: scalar — Maximum allowed value.

**Use Cases:**
- Capping outliers in data.
- Bounding values in image processing.
- Keeping predictions within thresholds.

**Example:**
```python
a = np.array([10, 50, 100])
np.clip(a, 25, 75)  # [25 50 75]
```

---